<?php
/**
 * AppointmentRepository — stage-2 write target (`bookingpress_appointment_bookings`).
 *
 * Inserted at confirm time per §M0.10. Subsequently updated post-insert with
 * the generated `bookingpress_booking_id` and `bookingpress_payment_id` so
 * the three tables (entries, appointment_bookings, payment_transactions) form
 * a consistent triangle.
 *
 * @package BookingPress\Vue3\Repositories
 * @see     docs/migration/LEGACY_BEHAVIOR_CONTRACT.md §M0.10
 */

namespace BookingPress\Vue3\Repositories;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class AppointmentRepository extends BaseRepository {

	// Appointment-status values. DISTINCT from the payment-status map on the
	// payment_transactions row (see PaymentTransactionRepository). Lite global
	// options expose 1-4; Pro appends 5 + 6 (class.bookingpress_pro_global_options.php).
	/** Approved / paid appointment. */
	const STATUS_APPROVED  = 1;
	/** Pending payment / admin approval. */
	const STATUS_PENDING   = 2;
	/** Canceled by user or admin. */
	const STATUS_CANCELED  = 3;
	/** Rejected by admin. */
	const STATUS_REJECTED  = 4;
	/** No-Show (Pro only). */
	const STATUS_NO_SHOW   = 5;
	/** Completed (Pro only). */
	const STATUS_COMPLETED = 6;

	/**
	 * @inheritDoc
	 */
	protected function table_suffix() {
		return 'bookingpress_appointment_bookings';
	}

	/**
	 * @inheritDoc
	 */
	protected function cache_namespace() {
		return 'appointments';
	}

	/**
	 * Insert a stage-2 appointment row.
	 *
	 * @param array $data Map of `bookingpress_*` column → value. Caller is
	 *                    responsible for matching the column shape (the M3
	 *                    `SubmissionService::finalize_booking()` builds the
	 *                    payload from the entries row + payment outcome).
	 *
	 * @return int The new `bookingpress_appointment_booking_id`, or 0 on failure.
	 */
	public function insert( array $data ) {
		global $wpdb;

		if ( ! isset( $data['bookingpress_created_at'] ) ) {
			$data['bookingpress_created_at'] = current_time( 'mysql' );
		}
		// Generate an opaque token if the caller didn't supply one. Legacy
		// reads this column for some cancellation flows; keeping it
		// populated avoids surprise NULLs.
		if ( $this->has_column( 'bookingpress_appointment_token' ) && empty( $data['bookingpress_appointment_token'] ) ) {
			$data['bookingpress_appointment_token'] = wp_generate_password( 20, false );
		}

		$data = $this->filter_to_existing_columns( $data );
		if ( empty( $data ) ) {
			return 0;
		}

		$ok = $wpdb->insert( $this->table(), $data );
		if ( false === $ok ) {
			return 0;
		}
		return (int) $wpdb->insert_id;
	}

	/**
	 * Update the appointment_bookings row with the payment-side identifiers
	 * generated by stage 2.
	 *
	 * @param int    $booking_id        The appointment_booking_id from {@see insert()}.
	 * @param int    $payment_id        `bookingpress_payment_logs.bookingpress_payment_log_id`.
	 * @param string $booking_ref       The customer-facing invoice id.
	 *
	 * @return bool
	 */
	public function update_payment_link( $booking_id, $payment_id, $booking_ref ) {
		$booking_id = (int) $booking_id;
		$payment_id = (int) $payment_id;
		if ( $booking_id <= 0 ) {
			return false;
		}
		global $wpdb;
		$update = array();
		if ( $this->has_column( 'bookingpress_payment_id' ) ) {
			$update['bookingpress_payment_id'] = $payment_id;
		}
		if ( $this->has_column( 'bookingpress_booking_id' ) ) {
			$update['bookingpress_booking_id'] = (string) $booking_ref;
		}
		if ( empty( $update ) ) {
			return false;
		}
		$ok = $wpdb->update(
			$this->table(),
			$update,
			array( 'bookingpress_appointment_booking_id' => $booking_id )
		);
		return false !== $ok;
	}

	/**
	 * Read one row by id.
	 *
	 * @param int $booking_id
	 *
	 * @return array<string, mixed>|null Raw row keyed by column name.
	 */
	public function find( $booking_id ) {
		$booking_id = (int) $booking_id;
		if ( $booking_id <= 0 ) {
			return null;
		}
		global $wpdb;
		$table = $this->table();
		$raw   = $wpdb->get_row(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
				"SELECT * FROM `{$table}` WHERE bookingpress_appointment_booking_id = %d LIMIT 1",
				$booking_id
			),
			ARRAY_A
		);
		return is_array( $raw ) ? $raw : null;
	}

	/**
	 * Find by the linked entry id (forward lookup after stage 2).
	 *
	 * @param int $entry_id
	 *
	 * @return array<string, mixed>|null
	 */
	public function find_by_entry( $entry_id ) {
		$entry_id = (int) $entry_id;
		if ( $entry_id <= 0 ) {
			return null;
		}
		global $wpdb;
		$table = $this->table();
		$raw   = $wpdb->get_row(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
				"SELECT * FROM `{$table}` WHERE bookingpress_entry_id = %d LIMIT 1",
				$entry_id
			),
			ARRAY_A
		);
		return is_array( $raw ) ? $raw : null;
	}

	/**
	 * Drop columns from $data that don't exist on this install's table.
	 *
	 * @param array $data
	 *
	 * @return array
	 */
	private function filter_to_existing_columns( array $data ) {
		$out = array();
		foreach ( $data as $col => $val ) {
			if ( $this->has_column( $col ) ) {
				$out[ $col ] = $val;
			}
		}
		return $out;
	}
}
